### ISSUE TITLE
site goal fails with :For 'properties/author', nil is not an object." and "For 'properties/comitter', nil is not an object.

### ISSUE THREAD

**Issue by Redrield** [github/maven-plugins#105]
This is the stack trace: 

```
ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.8:site (default) on project TitleAPI: Error creating commit: Invalid request.
[ERROR] 
[ERROR] For 'properties/author', nil is not an object.
[ERROR] For 'properties/committer', nil is not an object. (422)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.github:site-maven-plugin:0.8:site (default) on project TitleAPI: Error creating commit: Invalid request.

For 'properties/author', nil is not an object.
For 'properties/committer', nil is not an object. (422)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating commit: Invalid request.

For 'properties/author', nil is not an object.
For 'properties/committer', nil is not an object. (422)
    at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:425)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 25 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/author', nil is not an object.
For 'properties/committer', nil is not an object. (422)
    at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:514)
    at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:605)
    at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:719)
    at org.eclipse.egit.github.core.service.DataService.createCommit(DataService.java:397)
    at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:419)
    ... 27 more
[ERROR]
```

**Comment by rsoika** [comment]
I had the same problem. After upgrade to version 0.12 the plugin works fine.

**Comment by karianna** [comment]
At 0.9 of the plugin but have the same issue as @Redrield

**Comment by llorllale** [comment]
+1
Issue exists in 0.9

**Comment by battis** [comment]
+1 issue exists in 0.9

For other Googlers:

  - Lots of people suggest setting your "real name" in your Google Profile. That isn't a field, or if it is, I've already set it.
  - Others suggest having a public email address in your GitHub profile. Tried it. Didn't work.
  - Tried using at token with full and complete access. No dice.

What **does** work: update to version 0.12 (which is not documented, and which IntelliJ doesn't believe exists):

```xml
<plugin>
                        <groupId>com.github.github</groupId>
                        <artifactId>site-maven-plugin</artifactId>
                        <version>0.12</version>
                        <configuration>
                            <message>Updating site</message>
                            <outputDirectory>target/apidocs</outputDirectory>
                            <noJekyll>true</noJekyll>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>site</goal>
                                </goals>
                                <phase>site-deploy</phase>
                            </execution>
                        </executions>
                    </plugin>
```
