### ISSUE TITLE
 Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4 (tests) on project elasticsearch

### ISSUE THREAD

**Issue by meghalidhoble** [github/maven-plugins#115]
**Environment Details:**
OS: Rhel 7.2
Platform: Linux PowerPC
Maven : 3.3.9 (latest)
Java : 1.8.0-91

**Steps:**
1. I have set the MAVEN_HOME, PATH, JAVA_HOME 
2. Run the "mvn clean package" command from the elasticsearch source code directory
3. Getting below trace:

**Error log**
Tests with failures [seed: 371EE79A51B4B92C]:
- org.elasticsearch.plugins.PluginManagerPermissionTests.testThatUnaccessibleBinDirectoryAbortsPluginInstallation
- org.elasticsearch.plugins.PluginManagerPermissionTests.testThatUnaccessiblePluginConfigDirectoryAbortsPluginInstallation
- org.elasticsearch.plugins.PluginManagerPermissionTests.testThatNonWritablePluginsDirectoryLeavesNoLeftOver

[INFO] JVM J0:     0.53 ..   104.23 =   103.71s
[INFO] JVM J1:     0.53 ..   104.09 =   103.56s
[INFO] JVM J2:     0.53 ..   104.17 =   103.64s
[INFO] Execution time total: 1 minute 44 seconds
[INFO] Tests summary: 565 suites (2 ignored), 3206 tests, 3 failures, 16 ignored (16 assumptions)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Build Tools and Resources .......................... SUCCESS [  0.957 s]
[INFO] Rest API Specification ............................. SUCCESS [  0.729 s]
[INFO] Elasticsearch: Parent POM .......................... SUCCESS [  8.714 s]
[INFO] Elasticsearch: Core ................................ FAILURE [02:41 min]
[INFO] Distribution: Parent POM ........................... SKIPPED
[INFO] Integration Test Package: ZIP ...................... SKIPPED
[INFO] Module: Parent POM ................................. SKIPPED
[INFO] Module: Language: Expression ....................... SKIPPED
[INFO] Module: Language: Groovy ........................... SKIPPED
[INFO] Module: Reindex .................................... SKIPPED
[INFO] Distribution: TAR .................................. SKIPPED
[INFO] Distribution: ZIP .................................. SKIPPED
[INFO] Distribution: Deb .................................. SKIPPED
[INFO] Distribution: RPM .................................. SKIPPED
[INFO] Plugin: Parent POM ................................. SKIPPED
[INFO] Plugin: Analysis: Japanese (kuromoji) .............. SKIPPED
[INFO] Plugin: Analysis: Smart Chinese (smartcn) .......... SKIPPED
[INFO] Plugin: Analysis: Polish (stempel) ................. SKIPPED
[INFO] Plugin: Analysis: Phonetic ......................... SKIPPED
[INFO] Plugin: Analysis: ICU .............................. SKIPPED
[INFO] Plugin: Cloud: Google Compute Engine ............... SKIPPED
[INFO] Plugin: Cloud: Azure ............................... SKIPPED
[INFO] Plugin: Cloud: AWS ................................. SKIPPED
[INFO] Plugin: Delete By Query ............................ SKIPPED
[INFO] Plugin: Discovery: Multicast ....................... SKIPPED
[INFO] Plugin: Language: JavaScript ....................... SKIPPED
[INFO] Plugin: Language: Python ........................... SKIPPED
[INFO] Plugin: Mapper: Attachments ........................ SKIPPED
[INFO] Plugin: Mapper: Murmur3 ............................ SKIPPED
[INFO] Plugin: Mapper: Size ............................... SKIPPED
[INFO] Plugin: JVM example ................................ SKIPPED
[INFO] Plugin: Example site ............................... SKIPPED
[INFO] QA: Parent POM ..................................... SKIPPED
[INFO] QA: Smoke Test Plugins ............................. SKIPPED
[INFO] QA: Smoke Test Multi-Node IT ....................... SKIPPED
[INFO] QA: Smoke Test Client .............................. SKIPPED
[INFO] QA: Smoke Test Command Line Params ................. SKIPPED
[INFO] QA: Smoke Test Reindex with Groovy ................. SKIPPED
[INFO] QA: Backwards Compatibility ........................ SKIPPED
[INFO] QA: BWC: Shared .................................... SKIPPED
[INFO] QA: BWC: Two Versions Parent ....................... SKIPPED
[INFO] QA: BWC: Current ................................... SKIPPED
[INFO] QA: BWC: 2.0 ....................................... SKIPPED
[INFO] QA: BWC: 2.1 ....................................... SKIPPED
[INFO] QA: BWC: 2.2 ....................................... SKIPPED
[INFO] QA: BWC: 2.3 ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:54 min
[INFO] Finished at: 2016-06-09T11:35:32+05:30
[INFO] Final Memory: 77M/2305M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4 (tests) on project elasticsearch: There were test failures: 565 suites (2 ignored), 3206 tests, 3 failures, 16 ignored (16 assumptions) [seed: 371EE79A51B4B92C] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4 (tests) on project elasticsearch: There were test failures: 565 suites (2 ignored), 3206 tests, 3 failures, 16 ignored (16 assumptions) [seed: 371EE79A51B4B92C]
       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
       at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
       at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
       at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
       at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: There were test failures: 565 suites (2 ignored), 3206 tests, 3 failures, 16 ignored (16 assumptions) [seed: 371EE79A51B4B92C]
       at com.carrotsearch.maven.plugins.junit4.JUnit4Mojo.execute(JUnit4Mojo.java:528)
       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
       ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :elasticsearch

**Comment by mprins** [comment]
this is not the place for your issue, talk to the elasticsearch people
