### ISSUE TITLE
Abuse detection mechanism when pushing to github from travis

### ISSUE THREAD

**Issue by Vad1mo** [github/maven-plugins#92]
since yesterday i get this exception:
```
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.10:site (default) on project website: Error creating blob: You have triggered an abuse detection mechanism and have been temporarily blocked from calling the API. Please retry your request again later. (403) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.github:site-maven-plugin:0.10:site (default) on project website: Error creating blob: You have triggered an abuse detection mechanism and have been temporarily blocked from calling the API. Please retry your request again later. (403)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating blob: You have triggered an abuse detection mechanism and have been temporarily blocked from calling the API. Please retry your request again later. (403)
	at com.github.maven.plugins.site.SiteMojo.createBlob(SiteMojo.java:293)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:356)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.eclipse.egit.github.core.client.RequestException: You have triggered an abuse detection mechanism and have been temporarily blocked from calling the API. Please retry your request again later. (403)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.eclipse.egit.github.core.service.DataService.createBlob(DataService.java:115)
	at com.github.maven.plugins.site.SiteMojo.createBlob(SiteMojo.java:289)
	... 22 more
```
 
It all worked the last months without any problems, I wonder if that can be related to the plugin, github or travis.

https://travis-ci.org/konik-io/website/builds/64462044

**Comment by bguerin** [comment]
Same as #17, #28 and #88 ...
fixed by #90

**Comment by Vad1mo** [comment]
is the fix  #90 released?

**Comment by jasonrudolph** [comment]
> is the fix #90 released? Or when is a release planned?

Yes. The [`0.12.0` release](https://github.com/github/maven-plugins/releases/tag/github-maven-plugins-parent-0.12) includes the fix from #90 and should resolve this issue.

/cc https://github.com/github/maven-plugins/pull/90#issuecomment-107713564
